test-pers.php File Reference
Variables
$debug = TRUE
$remote = `user@example.com`
$password = `password`
$workdir = `/tmp`
$tmpfname = tempnam($workdir, open-)
$fp = fopen($tmpfname, `w`)
$child_stdout = tempnam($workdir, `open_sh-O-`)
$child_stderr = tempnam($workdir, `open_sh-E-`)
$descriptorspec
$process
$f = popen(`ssh -x -t -t -S /tmp/open-sock $remote ls`, `w`)
Variable Documentation
$child_stderr = tempnam($workdir, `open_sh-E-`)
Definition at line 28 of file test-pers.php.
$child_stdout = tempnam($workdir, `open_sh-O-`)
Definition at line 27 of file test-pers.php.
$debug = TRUE
Definition at line 3 of file test-pers.php.
Referenced by ssh_open().
$descriptorspec
Initial value:
 array(
    0 => array("pipe", "r"),  // connect childs stdin to the read end of a pipe
    1 => array("file", $child_stdout, "a"),  // connect childs stdout to the write end of a pipe
    2 => array("file", $child_stderr, "a")   // stderr is a pipe to read from
)
Definition at line 30 of file test-pers.php.
Referenced by ssh_open().
$f = popen(`ssh -x -t -t -S /tmp/open-sock $remote ls`, `w`)
Definition at line 52 of file test-pers.php.
$fp = fopen($tmpfname, `w`)
Definition at line 18 of file test-pers.php.
Referenced by do_scp(), do_ssh(), ssh_copy(), ssh_open(), and ssh_passthru().
$password = `password`
Definition at line 5 of file test-pers.php.
$process
Initial value:
 proc_open("ssh -x -t -t -M -S /tmp/open-sock $remote", 
                 $descriptorspec,
                 $pipes)
Definition at line 38 of file test-pers.php.
Referenced by ssh_open().
$remote = `user@example.com`
Definition at line 4 of file test-pers.php.
$tmpfname = tempnam($workdir, open-)
Definition at line 10 of file test-pers.php.
Referenced by do_scp(), do_ssh(), ssh_copy(), ssh_open(), and ssh_passthru().
$workdir = `/tmp`
Definition at line 6 of file test-pers.php.