SExec Class Reference
Public Member Functions
SExec ($remote=`localhost`, $password=`xxyzzy`)
set_remote_end ($remote, $password=`xxyzzy`)
ssh_passthru ($remote, $password, $command, &$status)
Execute a single command remotely using ssh and display its output, optionally returning its exit status (like passthru).
ssh_exec ($remote, $password, $command, &$out)
Execute a remote command using SSH.
ssh_copy ($origin, $destination, $password)
Copy a file or directory from one source to a destination.
ssh_open_shell ($remote, $password)
Open an SSH connection to a remote site with a shell to run interactive commands.
ssh_open_command ($remote, $password, $command)
Open an SSH connection to run an interactive command on a remote site.
ssh_close ($p)
Close an SSH interactive session.
ssh_get_status ($p)
get info about a running ssh_open_* process
ssh_popen ($remote, $password, $command, $mode)
Execute a remore command and keep an unidirectional stream contact with it.
ssh_pclose ($f)
Public Attributes
$version = `1.0`
$remote
$password
$ssh = `/usr/bin/ssh`
$scp = `/usr/bin/scp`
Constructor & Destructor Documentation
SExec::SExec ($ remote = `localhost`, $ password = `xxyzzy`)
Definition at line 12 of file ssh.php.
References $remote.
Member Function Documentation
SExec::set_remote_end ($ remote, $ password = `xxyzzy`)
Definition at line 18 of file ssh.php.
References $password, and $remote.
SExec::ssh_close ($ p)
Close an SSH interactive session.
Definition at line 417 of file ssh.php.
References $debug.
Referenced by Grid::pjob_get_id().
SExec::ssh_copy ($ origin, $ destination, $ password)
Copy a file or directory from one source to a destination.
This function copies source to dest, where one of them is a local filespec and the other a remote filespec of the form [user@]host:path
If the original source is a directory, it will be copied recursively to destination (hence easing file transfers).
The function returns TRUE on success or FALSE on failure.
Parameters:
origin The origin path, of the form [user@][host][:port]path You may omit the optional sections if the default values (local username, local host, standard SSH port) are OK
destination The destination path, of the form [user@][host][:port:]path You may omit the optional sections if the default values (local username, local host, standard SSH port) are OK
password The password to use to connect to the remote end of the copy (be it the origin or the destination, it's all the same). If connection is automatic by some means (.shosts or RSA/DSA authentication) then it should be ignored and any password should do.
Returns: status TRUE if all went well, or FALSE on failure.
Definition at line 183 of file ssh.php.
References $debug, and $status.
SExec::ssh_exec ($ remote, $ password, $ command, &$ out)
Execute a remote command using SSH.
This function sort of mimics rexec(3) using SSH as the transport protocol.
The function returns the exit status of the remote command, and appends the remote job output to an optional argument.
This function is intended to be used as a one-time all-at-once non-interactive execution mechanism which will run the command remotely and return its output.
If you try to issue an interactive command using this function, all you will get is unneccessary trouble. So don't!
Parameters:
remote The remote end to run the command, in the form 'user:port' (you may omit the 'user@' or ':port' parts if the default values [i.e. same user or standard port] are OK).
password The remote password. Note that if direct RSA/DSA/.shosts/.rhosts login is enabled then the password should be ignored as SSH should not run the ASKPASS command).
command The command to execute on the remote end NOTE: if you want to use redirection, the entire remote command line should be enclosed in additional quotes!
output Optional, the collated (stdout+stderr) output of the remote command.
Returns: status will hold the termination status of SSH after invocation, which should be the exit status of the remote command or 255 if an error occurred
Definition at line 130 of file ssh.php.
References $debug.
Referenced by Grid::pjob_retrieve().
SExec::ssh_get_status ($ p)
get info about a running ssh_open_* process
Definition at line 442 of file ssh.php.
SExec::ssh_open_command ($ remote, $ password, $ command)
Open an SSH connection to run an interactive command on a remote site.
Connects to a remote host and runs an interactive command with NO controlling terminal.
Returns a process_control array which contains the process resource ID and an the standard file descriptors which the caller may use to interact with the remote shell.
Definition at line 329 of file ssh.php.
References $debug.
SExec::ssh_open_shell ($ remote, $ password)
Open an SSH connection to a remote site with a shell to run interactive commands.
Connects to a remote host and opens an interactive shell session with NO controlling terminal.
Returns a process_control array which contains the process resource ID and an the standard file descriptors which the caller may use to interact with the remote shell.
Parameters:
remote The remote end to run the shell, in the form 'user:port' (you may omit the 'user@' or ':port' parts if the default values [i.e. same user or standard port] are OK).
password The remote password. Note that if direct RSA/DSA/.shosts/.rhosts login is enabled then the password should be ignored as SSH should not run the ASKPASS command).
Definition at line 224 of file ssh.php.
References $debug.
SExec::ssh_passthru ($ remote, $ password, $ command, &$ status)
Execute a single command remotely using ssh and display its output, optionally returning its exit status (like passthru).
This function is intended to be used as a one-time all-at-once non-interactive execution mechanism which will run the command remotely and display its output.
If you try to issue an interactive command using this function, all you will get is unneccessary trouble. So don't!
This might be done as well using a pipe on /tmp and making the command 'cat' the pipe: when ssh runs, it runs the command 'cat' on the pipe and hangs on read. Then we just need a thread to open the pipe, put the password and close the pipe. This other way the password is never wirtten down. But, OTOH, the file life is so ephemeral that most of the time it will only exist in the internal system cache, so this approach is not that bad either.
Parameters:
remote The remote end to run the command, in the form 'user:port' (you may omit the 'user@' or ':port' parts if the default values [i.e. same user or standard port] are OK).
password The remote password. Note that if direct RSA/DSA/.shosts/.rhosts login is enabled then the password should be ignored as SSH should not run the ASKPASS command).
command The command to execute on the remote end NOTE: if you want to use redirection, the entire remote command line should be enclosed in additional quotes!
status Optional, this will hold the termination status of SSH after invocation, which should be the exit status of the remote command or 255 if an error occurred
Returns: void
Definition at line 67 of file ssh.php.
References $debug.
SExec::ssh_pclose ($ f)
Definition at line 477 of file ssh.php.
SExec::ssh_popen ($ remote, $ password, $ command, $ mode)
Execute a remore command and keep an unidirectional stream contact with it.
This routine mimics 'popen()' but uses ssh to connect to a remote host and run the requested command.
Definition at line 455 of file ssh.php.
References $debug.
Referenced by Grid::pjob_get_id().
Member Data Documentation
SExec::$password
Definition at line 7 of file ssh.php.
Referenced by set_remote_end().
SExec::$remote
Definition at line 6 of file ssh.php.
Referenced by set_remote_end(), and SExec().
SExec::$scp = `/usr/bin/scp`
Definition at line 10 of file ssh.php.
SExec::$ssh = `/usr/bin/ssh`
Definition at line 9 of file ssh.php.
SExec::$version = `1.0`
Definition at line 5 of file ssh.php.
The documentation for this class was generated from the following file:
ssh.php