Grid Class Reference
Public Member Functions
Grid ()
Constructor for the class.
destruct ()
set_user ($user)
set the Grid user name
set_host ($host)
set the name of the Grid access host
set_password ($pass)
set the password for the remote grid user/server
set_passphrase ($pass)
set the passphrase for the remote grid user
set_work_dir ($wd)
set working directory on the Grid server
set_error_log ($errlog)
set error log
get_connection_status ()
get grid connection status
get_init_status ()
get grid initialization status
connect ()
open a persistent connection to the Grid UI server
initialize ($hours=12, $minutes=0)
Start the Grid services.
destroy ()
Destroy remote grid identity.
session_new ($hint=`sess`)
Create a new session.
session_define ($session, $directory)
Define an already existing session.
session_is_valid ($session='default')
check if supplied argument is a valid (existing and active) session.
session_directory ($session='default')
return the directory associated to a session
session_list_all ()
list all existing sessions (debugging only)
session_destroy ($session='default')
destroy the specified session
session_destroy_all ()
Destroy all existing sessions.
job_submit_set_timeout ($seconds=0)
Set maximum (guesstimated) allowed time for a job submission to succeed.
job_submit ($job, &$out, $session='default')
submit a job to the grid
job_get_id ($job, $session='default')
Get Grid ID of a submitted job.
job_status ($job, &$out, $session='default')
check job status
job_get_output ($job, &$out, $session='default')
retrieve results
job_cancel ($job, &$out, $session='default')
Cancel a job previously submitted to the grid.
Grid ()
Constructor for the class.
destruct ()
set_user ($user)
set the Grid user name
set_host ($host)
set the name of the Grid access host
set_password ($pass)
set the password for the remote grid user/server
set_passphrase ($pass)
set the passphrase for the remote grid user
set_work_dir ($wd)
set working directory on the Grid server
set_error_log ($errlog)
set error log
get_connection_status ()
get grid connection status
get_init_status ()
get grid initialization status
connect ()
open a persistent connection to the Grid UI server
initialize ($hours=12, $minutes=0)
Start the Grid services.
destroy ()
Destroy remote grid identity.
session_new ($hint=`sess`)
Create a new session.
session_define ($session, $directory)
Define an already existing session.
session_is_valid ($session='default')
check if supplied argument is a valid (existing and active) session.
session_directory ($session='default')
return the directory associated to a session
session_list_all ()
list all existing sessions (debugging only)
session_destroy ($session='default')
destroy the specified session
session_destroy_all ()
Destroy all existing sessions.
job_submit_set_timeout ($seconds=0)
Set maximum (guesstimated) allowed time for a job submission to succeed.
job_submit ($job, &$out, $session='default')
submit a job to the grid
job_get_id ($job, $session='default')
Get Grid ID of a submitted job.
job_status ($job, &$out, $session='default')
check job status
job_get_output ($job, &$out, $session='default')
retrieve results
job_cancel ($job, &$out, $session='default')
Cancel a job previously submitted to the grid.
Public Attributes
$entry_point
the grid entry point, should not be needed
$username
user name to use to connect to the grid
$hostname
name of host that provides access to the grid
$password
password to login on the UI node
$passphrase
key to unlock the grid access certificate
$work_dir
a GrUI directory where we can work
$error_log
a local file to store the error log
$std_in
Standard input of the grid entry.
$std_out
Standard output of the grid entry.
$std_err
Standard error of the grid entry.
$connected
$initialized
$sessions
$sx
$submit_timeout
Constructor & Destructor Documentation
Grid::Grid ()
Constructor for the class.
Set the values for the class variables using defaults provided in 'config.php'
These defaults can be overridden using the functions provided below.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`;
Returns: Grid a new instance of a Grid class object
Definition at line 399 of file src/grid.php.
References $debug_grid.
Grid::Grid ()
Constructor for the class.
Set the values for the class variables using defaults provided in 'config.php'
These defaults can be overridden using the functions provided below.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`;
Returns: Grid a new instance of a Grid class object
Definition at line 399 of file test/grid.php.
References $debug_grid.
Member Function Documentation
Grid::connect ()
open a persistent connection to the Grid UI server
The Grid User Interface Server is the entry point to the Grid for users and user applications. This is where jobs are launched from.
This package has been designed to be able to be installed in any host, independent of whether it is an UI or not. Thus, to be able to submit jobs to the Grid, the server hosting the Web UI must connect to a Grid UI host to do the work.
This routine opens a connection to a Grid UI host using an specified username (i.e. all jobs will be run under said username).
The panorama therefore will look like this:
HTML front-end --> processor.php <--> SSH <--> remote host <--> Grid
This allows for better resilience: should a GridUI host be unavailable, we can detect the error condition and try another one. If the GridUI runs the front-end, then we have a single point of failure, which is a no-no.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid;
$eg->pconnect(); if ($eg->get_connection_status()(p.) == FALSE) echo `Couldn't instantiate a new Grid!\n`;
Note: Use files instead of pipes and open them after securing thew connection: this should do with deadlocks and leave a trace log.
Returns: TRUE on success, FALSE otherwise.
Definition at line 788 of file test/grid.php.
Grid::connect ()
open a persistent connection to the Grid UI server
The Grid User Interface Server is the entry point to the Grid for users and user applications. This is where jobs are launched from.
This package has been designed to be able to be installed in any host, independent of whether it is an UI or not. Thus, to be able to submit jobs to the Grid, the server hosting the Web UI must connect to a Grid UI host to do the work.
This routine opens a connection to a Grid UI host using an specified username (i.e. all jobs will be run under said username).
The panorama therefore will look like this:
HTML front-end --> processor.php <--> SSH <--> remote host <--> Grid
This allows for better resilience: should a GridUI host be unavailable, we can detect the error condition and try another one. If the GridUI runs the front-end, then we have a single point of failure, which is a no-no.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid;
$eg->pconnect(); if ($eg->get_connection_status()(p.) == FALSE) echo `Couldn't instantiate a new Grid!\n`;
Note: Use files instead of pipes and open them after securing thew connection: this should do with deadlocks and leave a trace log.
Returns: TRUE on success, FALSE otherwise.
Definition at line 788 of file src/grid.php.
Referenced by session_list_all().
Grid::destroy ()
Destroy remote grid identity.
Destroy the certification we initialized so that no more jobs can be launched under our identity.
This may be called even if we haven't called 'Grid::initialize()' because there may exits a previous activation that is still valid and we want to destroy it.
To make things clear:
Grid::initialize()(p.) `opens` the `door` to the Grid for the user during a given time. New calls from the same user in this or any other login session, from this or any other site, while the `door` is open, share the same `door` and simply extend its validity period.
Grid::destroy()(p.) `closes` the currently open door. If the door was being shared by more login sessions, it is closed for all of them, not just the caller, and hence nor the caller, nor any process under the same user will be able to use the grid any longer unless Grid::initialize()(p.) is called again to open the door again (issue a new certificate).
In other words, you don't close a Grid `door`, you close the Grid `door`, and if it casually is being shared with other work sessions, then ALL of them will be destroyed (meaning that other active work sessions will fail).
Thus: be careful when using this method. Be very careful.
Sessions should be initiated using a validity length that you guesstimate will be comfortably enough for running all your work and left to expire by themselves.
Grid::destroy()(p.) should only be called when you are sure that you don't want any work on the Grid to be accepted on your behalf, neither from this not other work sessions.
So, in general, it is better to make good estimations of the time needed by your jobs and specify it to Grid::initialize()(p.) and not use Grid::destroy()(p.) unless there are good reasons.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK`; $eg->destroy()(p.); $eg->disconnect();
Note: Be careful when using this function: as it destroys our Grid-ID, no more work will be able to be executed on the grid on our behalf. In other words, please, make sure there is no work pending and that all your work has terminated before destroying your Grid-ID.
Returns: bool TRUE on success, FALSE on failure
Definition at line 1035 of file test/grid.php.
References $debug_grid.
Grid::destroy ()
Destroy remote grid identity.
Destroy the certification we initialized so that no more jobs can be launched under our identity.
This may be called even if we haven't called 'Grid::initialize()' because there may exits a previous activation that is still valid and we want to destroy it.
To make things clear:
Grid::initialize()(p.) `opens` the `door` to the Grid for the user during a given time. New calls from the same user in this or any other login session, from this or any other site, while the `door` is open, share the same `door` and simply extend its validity period.
Grid::destroy()(p.) `closes` the currently open door. If the door was being shared by more login sessions, it is closed for all of them, not just the caller, and hence nor the caller, nor any process under the same user will be able to use the grid any longer unless Grid::initialize()(p.) is called again to open the door again (issue a new certificate).
In other words, you don't close a Grid `door`, you close the Grid `door`, and if it casually is being shared with other work sessions, then ALL of them will be destroyed (meaning that other active work sessions will fail).
Thus: be careful when using this method. Be very careful.
Sessions should be initiated using a validity length that you guesstimate will be comfortably enough for running all your work and left to expire by themselves.
Grid::destroy()(p.) should only be called when you are sure that you don't want any work on the Grid to be accepted on your behalf, neither from this not other work sessions.
So, in general, it is better to make good estimations of the time needed by your jobs and specify it to Grid::initialize()(p.) and not use Grid::destroy()(p.) unless there are good reasons.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK`; $eg->destroy()(p.); $eg->disconnect();
Note: Be careful when using this function: as it destroys our Grid-ID, no more work will be able to be executed on the grid on our behalf. In other words, please, make sure there is no work pending and that all your work has terminated before destroying your Grid-ID.
Returns: bool TRUE on success, FALSE on failure
Definition at line 1038 of file src/grid.php.
References $debug_grid.
Grid::destruct ()
Definition at line 416 of file test/grid.php.
References $debug_grid.
Grid::destruct ()
Definition at line 416 of file src/grid.php.
References $debug_grid.
Grid::get_connection_status ()
get grid connection status
This method allows you to know if the connection with the remote grid entry point has been successfully established or not. Note that this does not mean you may launch jobs to the grid: you still need to initialize the grid first.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid;
$eg->pconnect(); if ($eg->get_connection_status()(p.) == FALSE) echo `Couldn't connect to the Grid entry point!\n`;
Returns: bool TRUE if the connection has been established, FALSE otherwise.
Definition at line 690 of file test/grid.php.
References $debug_grid.
Grid::get_connection_status ()
get grid connection status
This method allows you to know if the connection with the remote grid entry point has been successfully established or not. Note that this does not mean you may launch jobs to the grid: you still need to initialize the grid first.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid;
$eg->pconnect(); if ($eg->get_connection_status()(p.) == FALSE) echo `Couldn't connect to the Grid entry point!\n`;
Returns: bool TRUE if the connection has been established, FALSE otherwise.
Definition at line 690 of file src/grid.php.
References $debug_grid.
Grid::get_init_status ()
get grid initialization status
This method allows you to learn whether the Grid has been successfully initialized and is ready to accept jobs. This entails both, login in as a specific user on the Grid connection point, and activating the proxy with your passphrase.
The reason for the two step process is that in order to activate the grid you need to identify yourself using a grid certificate emitted by a CA. But to activate it you need an account on a grid access machine, which is open by any local administrator. Since this account is not under the central CA control, we can't trust it to submit jobs and require a proxy-initialization with an appropriate passphrase.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid;
$eg->initialize()(p.); if ($eg->get_init_status()(p.) == FALSE) echo `Couldn't initialize the Grid!\n`;
Returns: bool TRUE if the grid has been initialized, FALSE otherwise.
Definition at line 731 of file test/grid.php.
References $debug_grid.
Grid::get_init_status ()
get grid initialization status
This method allows you to learn whether the Grid has been successfully initialized and is ready to accept jobs. This entails both, login in as a specific user on the Grid connection point, and activating the proxy with your passphrase.
The reason for the two step process is that in order to activate the grid you need to identify yourself using a grid certificate emitted by a CA. But to activate it you need an account on a grid access machine, which is open by any local administrator. Since this account is not under the central CA control, we can't trust it to submit jobs and require a proxy-initialization with an appropriate passphrase.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid;
$eg->initialize()(p.); if ($eg->get_init_status()(p.) == FALSE) echo `Couldn't initialize the Grid!\n`;
Returns: bool TRUE if the grid has been initialized, FALSE otherwise.
Definition at line 731 of file src/grid.php.
References $debug_grid.
Grid::initialize ($ hours = 12, $ minutes = 0)
Start the Grid services.
This function starts the grid services on the remote UI server host. This is done by unlocking the certificate that we are going to use to run our jobs on the grid using the passphrase provided.
Grid services have a lifetime of their own. By default they are available for 12:00 hours (that's the default value of grid-proxy-init itself), but their duration may be fine tuned if we have some knowledge about the time required to run our job.
Grid opening time is specified in hours+minutes. If the number of minutes is negative, the specified minutes are substracted from the specified hours (e.g: 1, -15 is fifteen minutes to one hour, i.e. 45 minutes). If the total time specified is negative then the default of 12:00 is used.
Grid::initialize()(p.) enables the grid for a specified amount of time (by default 12:00h). This means that during the validity period, the user on the Grid-UI host may access the grid, in the same or different logins. The validity period SURVIVES after we close all communications with the remote grid entry point for as long as we have specified (so our jobs may continue running).
If Grid access was already available (by a previous call to Grid::initialize()(p.)) when we issue the call, then it is reused and extended to acommodate the newly requested validity period. In other words, the Grid access is shared among all logins during its lifetime.
This also means that if a valid certificate has been issued and not expired yet (another call to Grid::initialize()(p.) is still valid), then we may submit jobs to the Grid without any need to call Grid::initialize()(p.) ourselves.
E.g., say you have a web-based service that runs a long job and you want to have the grid enabled 12h (the default). You just call Grid::initialize()(p.) and then submit the job.
Now say that before it expires, someone logs in on your account but shouldn't have access to the Grid (i.e. they don't know the Grid-activation passphrase). Since the grid is already activated, they CAN submit jobs on your behalf even if they should not.
Therefore, DO NOT SHARE YOUR ACCOUNT ON THE GRID-UI WITH ANYBODY. Protect it as dearly as your Grid certificate.
It also means that debugging may be somewhat convoluted, as a call to Grid::initialize()(p.) may fail and jobs could still be accepted if another call from some other process is still valid. While debugging, it is better if you review the command output and make sure it shows how the call fared.
So, what happens if we destroy a session? See Grid::destroy()(p.) for more details.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); $eg->connect()(p.); if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; $eg->destroy()(p.); $eg->disconnect();
Note: the output of the grid initialization command will go to our standard output (i.e. the web server)!
Bug : XXX JR XXX grid-proxy-init will use the time from the last issued command. To avoid setting a time shorter than one already existing we should first issue a grid-proxy-info, check if there is a running proxy, its time left, see if it is longer than what we want to set and if it is, then do NOTHING to avoid setting it shorter.
Parameters:
integer Estimated duration in hours of the session
integer Estimated duration in minutes of the session
Returns: bool TRUE on success, FALSE otherwise
Definition at line 903 of file test/grid.php.
Grid::initialize ($ hours = 12, $ minutes = 0)
Start the Grid services.
This function starts the grid services on the remote UI server host. This is done by unlocking the certificate that we are going to use to run our jobs on the grid using the passphrase provided.
Grid services have a lifetime of their own. By default they are available for 12:00 hours (that's the default value of grid-proxy-init itself), but their duration may be fine tuned if we have some knowledge about the time required to run our job.
Grid opening time is specified in hours+minutes. If the number of minutes is negative, the specified minutes are substracted from the specified hours (e.g: 1, -15 is fifteen minutes to one hour, i.e. 45 minutes). If the total time specified is negative then the default of 12:00 is used.
Grid::initialize()(p.) enables the grid for a specified amount of time (by default 12:00h). This means that during the validity period, the user on the Grid-UI host may access the grid, in the same or different logins. The validity period SURVIVES after we close all communications with the remote grid entry point for as long as we have specified (so our jobs may continue running).
If Grid access was already available (by a previous call to Grid::initialize()(p.)) when we issue the call, then it is reused and extended to acommodate the newly requested validity period. In other words, the Grid access is shared among all logins during its lifetime.
This also means that if a valid certificate has been issued and not expired yet (another call to Grid::initialize()(p.) is still valid), then we may submit jobs to the Grid without any need to call Grid::initialize()(p.) ourselves.
E.g., say you have a web-based service that runs a long job and you want to have the grid enabled 12h (the default). You just call Grid::initialize()(p.) and then submit the job.
Now say that before it expires, someone logs in on your account but shouldn't have access to the Grid (i.e. they don't know the Grid-activation passphrase). Since the grid is already activated, they CAN submit jobs on your behalf even if they should not.
Therefore, DO NOT SHARE YOUR ACCOUNT ON THE GRID-UI WITH ANYBODY. Protect it as dearly as your Grid certificate.
It also means that debugging may be somewhat convoluted, as a call to Grid::initialize()(p.) may fail and jobs could still be accepted if another call from some other process is still valid. While debugging, it is better if you review the command output and make sure it shows how the call fared.
So, what happens if we destroy a session? See Grid::destroy()(p.) for more details.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); $eg->connect()(p.); if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; $eg->destroy()(p.); $eg->disconnect();
Note: the output of the grid initialization command will go to our standard output (i.e. the web server)!
Bug : XXX JR XXX grid-proxy-init will use the time from the last issued command. To avoid setting a time shorter than one already existing we should first issue a grid-proxy-info, check if there is a running proxy, its time left, see if it is longer than what we want to set and if it is, then do NOTHING to avoid setting it shorter.
Parameters:
integer Estimated duration in hours of the session
integer Estimated duration in minutes of the session
Returns: bool TRUE on success, FALSE otherwise
Definition at line 903 of file src/grid.php.
Grid::job_cancel ($ job, &$ out, $ session = 'default')
Cancel a job previously submitted to the grid.
Note: If the job has not reached the CE yet (i.e.: its status is WAITING or READY states), the cancellation request may be ignored, and the job may continue running, although a message of successful cancellation is returned to the user. In such cases, just cancel the job again when its status is SCHEDULED or RUNNING
Parameters:
string The name of the job you submitted to the grid
string Optionally identifies the session to which the job belongs (if it was submitted within one). If this is not specified, then the default session is used.
Returns: bool TRUE on success, FALSE on failure.
Definition at line 1946 of file test/grid.php.
Grid::job_cancel ($ job, &$ out, $ session = 'default')
Cancel a job previously submitted to the grid.
Note: If the job has not reached the CE yet (i.e.: its status is WAITING or READY states), the cancellation request may be ignored, and the job may continue running, although a message of successful cancellation is returned to the user. In such cases, just cancel the job again when its status is SCHEDULED or RUNNING
Parameters:
string The name of the job you submitted to the grid
string Optionally identifies the session to which the job belongs (if it was submitted within one). If this is not specified, then the default session is used.
Returns: bool TRUE on success, FALSE on failure.
Definition at line 1949 of file src/grid.php.
Grid::job_get_id ($ job, $ session = 'default')
Get Grid ID of a submitted job.
You should not need this function normally. The job and session names you already have should actually be enough for all your needs. The function is needed internally by the class, but otherwise it should be of little interest.
Nevertheless, you may want to have access to this knowledge, either out of curiosity or for other reasons (e.g. re-routing access to a job through other access points after a crash of the original access point you used to submit it).
Indeed, this will come handy for newer releases of this class when disaster recovery is added. Meanwhile, as already said, it is of little use.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; echo `Submitting tst-job... `; if (! $eg->job_submit(`tst-job`, $out)) echo `error: coudn't start the job\n`; else echo `OK\n`; print_r($out); print_r($eg->job_get_id(`tst-job`));
Parameters:
string The name of the job you submitted to the grid
string Optionally identifies the session to which the job belongs (if it was submitted within one).
Returns: array|false with the known job-id's submitted from this 'job'. That looks as an oxymoron: there should only be one. Ergo, you may use it to detect job name clashes or job re-submissions.
Note: this is nasty and should be enhanced on a future version.
Definition at line 1607 of file test/grid.php.
Grid::job_get_id ($ job, $ session = 'default')
Get Grid ID of a submitted job.
You should not need this function normally. The job and session names you already have should actually be enough for all your needs. The function is needed internally by the class, but otherwise it should be of little interest.
Nevertheless, you may want to have access to this knowledge, either out of curiosity or for other reasons (e.g. re-routing access to a job through other access points after a crash of the original access point you used to submit it).
Indeed, this will come handy for newer releases of this class when disaster recovery is added. Meanwhile, as already said, it is of little use.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; echo `Submitting tst-job... `; if (! $eg->job_submit(`tst-job`, $out)) echo `error: coudn't start the job\n`; else echo `OK\n`; print_r($out); print_r($eg->job_get_id(`tst-job`));
Parameters:
string The name of the job you submitted to the grid
string Optionally identifies the session to which the job belongs (if it was submitted within one).
Returns: array|false with the known job-id's submitted from this 'job'. That looks as an oxymoron: there should only be one. Ergo, you may use it to detect job name clashes or job re-submissions.
Note: this is nasty and should be enhanced on a future version.
Definition at line 1610 of file src/grid.php.
Grid::job_get_output ($ job, &$ out, $ session = 'default')
retrieve results
Retrieve the results of a job from the Grid. This function will attempt to retrieve the results of a job. This relies on the results being already available, i.e. you better check the job status first and make sure it has completed.
If you don't, and the job hasn't completed yet, don't worry: nothing will be retrieved. So, no harm done. But you should check stdout to verify the condition.
All results will be stored remotely on the job directory, under a subdirectory with a unique name of the form $grid_user_name_XXXXX... where the X's mean a random string. Locally you will see them as $job/job_output so that they have an easy name to identify them.
To access your job output, just open this $job/output directory and look inside.
The rationale for this is to avoid overwriting your job information with its output. If that was intended, nothing is lost, just pick-up the newly generated file. This way you always have continued access to your old, submitted data for checking.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; echo `Submitting tst-job... `; if (! $eg->job_submit(`tst-job`, $out)) echo `error: coudn't start the job\n`; else echo `OK\n`; print_r($out); echo `\nGetting job ID... \n`; print_r($eg->job_get_id(`tst-job`)); echo `\nGetting job status... \n`; print_r($eg->job_status(`tst-job`, $out)); echo `\nGetting job output... `; if (! $eg->job_get_output(`tst-job`, $out)) echo `error: couldn't get job output\n`; else echo `OK\n`; print_r($out);
Parameters:
string The name of the job you submitted to the grid
string Optionally identifies the session to which the job belongs (if it was submitted within one). If this is not specified, then the default session is used.
Returns: bool TRUE on success, FALSE on failure.
Definition at line 1854 of file test/grid.php.
References $debug_grid.
Grid::job_get_output ($ job, &$ out, $ session = 'default')
retrieve results
Retrieve the results of a job from the Grid. This function will attempt to retrieve the results of a job. This relies on the results being already available, i.e. you better check the job status first and make sure it has completed.
If you don't, and the job hasn't completed yet, don't worry: nothing will be retrieved. So, no harm done. But you should check stdout to verify the condition.
All results will be stored remotely on the job directory, under a subdirectory with a unique name of the form $grid_user_name_XXXXX... where the X's mean a random string. Locally you will see them as $job/job_output so that they have an easy name to identify them.
To access your job output, just open this $job/output directory and look inside.
The rationale for this is to avoid overwriting your job information with its output. If that was intended, nothing is lost, just pick-up the newly generated file. This way you always have continued access to your old, submitted data for checking.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; echo `Submitting tst-job... `; if (! $eg->job_submit(`tst-job`, $out)) echo `error: coudn't start the job\n`; else echo `OK\n`; print_r($out); echo `\nGetting job ID... \n`; print_r($eg->job_get_id(`tst-job`)); echo `\nGetting job status... \n`; print_r($eg->job_status(`tst-job`, $out)); echo `\nGetting job output... `; if (! $eg->job_get_output(`tst-job`, $out)) echo `error: couldn't get job output\n`; else echo `OK\n`; print_r($out);
Parameters:
string The name of the job you submitted to the grid
string Optionally identifies the session to which the job belongs (if it was submitted within one). If this is not specified, then the default session is used.
Returns: bool TRUE on success, FALSE on failure.
Definition at line 1857 of file src/grid.php.
References $debug_grid.
Grid::job_status ($ job, &$ out, $ session = 'default')
check job status
This routine retrieves the job status report from the remote grid entry point into your local job directory, and returns the status of your specified job/session.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; echo `Submitting tst-job... `; if (! $eg->job_submit(`tst-job`, $out)) echo `error: coudn't start the job\n`; else echo `OK\n`; print_r($out); echo `\nGetting job ID... \n`; print_r($eg->job_get_id(`tst-job`)); echo `\nGetting job status... \n`; print_r($eg->job_status(`tst-job`, $out));
Parameters:
string The name of the job you submitted to the grid
string Output of the status request program. Useful for debugging.
string Optionally identifies the session to which the job belongs (if it was submitted within one).
Returns: array|false an array containing the job status or FALSE on failure.
Definition at line 1718 of file test/grid.php.
Grid::job_status ($ job, &$ out, $ session = 'default')
check job status
This routine retrieves the job status report from the remote grid entry point into your local job directory, and returns the status of your specified job/session.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; echo `Submitting tst-job... `; if (! $eg->job_submit(`tst-job`, $out)) echo `error: coudn't start the job\n`; else echo `OK\n`; print_r($out); echo `\nGetting job ID... \n`; print_r($eg->job_get_id(`tst-job`)); echo `\nGetting job status... \n`; print_r($eg->job_status(`tst-job`, $out));
Parameters:
string The name of the job you submitted to the grid
string Output of the status request program. Useful for debugging.
string Optionally identifies the session to which the job belongs (if it was submitted within one).
Returns: array|false an array containing the job status or FALSE on failure.
Definition at line 1721 of file src/grid.php.
Grid::job_submit ($ job, &$ out, $ session = 'default')
submit a job to the grid
This procedure submits a job to the Grid, optionally tagging it as part of a specific session.
A job must be stored in a single directory (whose name you provide in the call to this function). The directory must contain any executables, libraries, configuration files/scripts, and input data needed to run your job.
In addition, there must be a JDL file called 'job.jdl' and describing the job to the grid using the JDL language.
Please note that only the job-directory name is used. If you provide a longer path, only the last component (the job directory name) will be used to identify your job remotely.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; echo `Submitting tst-job... `; if (! $eg->job_submit(`tst-job`, $out)) echo `error: coudn't start the job\n`; else echo `OK\n`; print_r($out); $eg->destroy()(p.); $eg->disconnect();
Note: in future instances we may provide routines to generate the JDL, possibly within a GridJob class of its own.
Parameters:
string The name of the job (same as the subdirectory it is in)
array A variable to hold any messages spitted by the submission procedure. Messages will be stored as an array of strings (one per line) without ending newlines.
string Optional name of the session to which this job belongs (obtained from a previous call to session_new).
Returns: bool TRUE if success, FALSE otherwise
Definition at line 1465 of file test/grid.php.
References $debug_grid.
Grid::job_submit ($ job, &$ out, $ session = 'default')
submit a job to the grid
This procedure submits a job to the Grid, optionally tagging it as part of a specific session.
A job must be stored in a single directory (whose name you provide in the call to this function). The directory must contain any executables, libraries, configuration files/scripts, and input data needed to run your job.
In addition, there must be a JDL file called 'job.jdl' and describing the job to the grid using the JDL language.
Please note that only the job-directory name is used. If you provide a longer path, only the last component (the job directory name) will be used to identify your job remotely.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/test/cless`); $eg->set_error_log(`/tmp/grid/test/cless/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) echo `error: couldn't init the grid\n`; else echo `OK\n`; echo `Submitting tst-job... `; if (! $eg->job_submit(`tst-job`, $out)) echo `error: coudn't start the job\n`; else echo `OK\n`; print_r($out); $eg->destroy()(p.); $eg->disconnect();
Note: in future instances we may provide routines to generate the JDL, possibly within a GridJob class of its own.
Parameters:
string The name of the job (same as the subdirectory it is in)
array A variable to hold any messages spitted by the submission procedure. Messages will be stored as an array of strings (one per line) without ending newlines.
string Optional name of the session to which this job belongs (obtained from a previous call to session_new).
Returns: bool TRUE if success, FALSE otherwise
Definition at line 1468 of file src/grid.php.
References $debug_grid.
Grid::job_submit_set_timeout ($ seconds = 0)
Set maximum (guesstimated) allowed time for a job submission to succeed.
This value is application and dataset dependent, will be of relevance in rare occasions (1/4000) and hence may as well be generous.
The default is 0 seconds (no timeout). You should make measures to ensure it is reasonable. If set to 0, no timeout will be used.
Unless set to 0, you will need to code some resubmission policy in your application.
Parameters:
integer $seconds timeout in seconds for job submission (defaults to 0, no timeout).
Definition at line 1407 of file test/grid.php.
References $debug_grid, and session_is_valid().
Grid::job_submit_set_timeout ($ seconds = 0)
Set maximum (guesstimated) allowed time for a job submission to succeed.
This value is application and dataset dependent, will be of relevance in rare occasions (1/4000) and hence may as well be generous.
The default is 0 seconds (no timeout). You should make measures to ensure it is reasonable. If set to 0, no timeout will be used.
Unless set to 0, you will need to code some resubmission policy in your application.
Parameters:
integer $seconds timeout in seconds for job submission (defaults to 0, no timeout).
Definition at line 1410 of file src/grid.php.
References $debug_grid, and session_is_valid().
Grid::session_define ($ session, $ directory)
Define an already existing session.
This is useful if the session already exists and we want to access it: we already know its directory name, and just want to associate a new name with the existing directory name.
Use e.g. when you are to submit a job from a WWW page and access the results from a different one: as the new page has no access to the status of the previous one, we need to rebuild it ourselves.
Parameters:
string session name
string subdirectory of $work_dir to be associated to that name
Definition at line 1261 of file test/grid.php.
References $debug_grid.
Grid::session_define ($ session, $ directory)
Define an already existing session.
This is useful if the session already exists and we want to access it: we already know its directory name, and just want to associate a new name with the existing directory name.
Use e.g. when you are to submit a job from a WWW page and access the results from a different one: as the new page has no access to the status of the previous one, we need to rebuild it ourselves.
Parameters:
string session name
string subdirectory of $work_dir to be associated to that name
Definition at line 1264 of file src/grid.php.
References $debug_grid.
Grid::session_destroy ($ session = 'default')
destroy the specified session
This method destroys all data associated with the specified session. Currently it does not kill its associated jobs, but deleted all their underlying data nevertheless.
Warning: passing an empty string or no argument will destroy the default session.
return bool TRUE if success, FALSE otherwise
Definition at line 1331 of file test/grid.php.
Grid::session_destroy ($ session = 'default')
destroy the specified session
This method destroys all data associated with the specified session. Currently it does not kill its associated jobs, but deleted all their underlying data nevertheless.
Warning: passing an empty string or no argument will destroy the default session.
return bool TRUE if success, FALSE otherwise
Definition at line 1334 of file src/grid.php.
Grid::session_destroy_all ()
Destroy all existing sessions.
private
Definition at line 1364 of file test/grid.php.
Grid::session_destroy_all ()
Destroy all existing sessions.
private
Definition at line 1367 of file src/grid.php.
Grid::session_directory ($ session = 'default')
return the directory associated to a session
DOES NO ERROR CHECKING FOR VALID SESSION
Parameters:
string a session name
Returns: string the associated directory name
private
Definition at line 1297 of file test/grid.php.
References $debug_grid.
Grid::session_directory ($ session = 'default')
return the directory associated to a session
DOES NO ERROR CHECKING FOR VALID SESSION
Parameters:
string a session name
Returns: string the associated directory name
private
Definition at line 1300 of file src/grid.php.
References $debug_grid.
Grid::session_is_valid ($ session = 'default')
check if supplied argument is a valid (existing and active) session.
Parameters:
string a session name
Returns: bool TRUE if the session could be found among the list of valid sessions, FALSE otherwise
private
Definition at line 1276 of file test/grid.php.
References $debug_grid.
Grid::session_is_valid ($ session = 'default')
check if supplied argument is a valid (existing and active) session.
Parameters:
string a session name
Returns: bool TRUE if the session could be found among the list of valid sessions, FALSE otherwise
private
Definition at line 1279 of file src/grid.php.
References $debug_grid.
Referenced by job_submit_set_timeout(), and session_list_all().
Grid::session_list_all ()
list all existing sessions (debugging only)
private
Definition at line 1309 of file test/grid.php.
References $debug_grid, connect(), and session_is_valid().
Grid::session_list_all ()
list all existing sessions (debugging only)
private
Definition at line 1312 of file src/grid.php.
References $debug_grid, connect(), and session_is_valid().
Grid::session_new ($ hint = `sess`)
Create a new session.
We take control of the session system: in a previous incarnation we got the session name from the user. This is dangerous since we can not avoid clashes even with random session names provided by a user: a randomly generated name may be guaranteed unique within the user's local host namespace, but should various calls come from different hosts (e.g. HA front-ends in a cluster), it is conceivable (although improbable) that both come up with the same random number and generate a clash on the shared remote grid access point. Hence the new approach: to be true, users do not need to generate a session name themselves: they just need a way to refer to them.
This routine will generate a new session: under a given session, we guarantee that processes will be run under an isolated sandbox where non name clashes from other concurrent users will occur. Name clashes within a given session induced by the user are still the responsability of the user.
SESSIONS
The basic idea is as follows: if you are developing a service that may be called concurrently by various users, your problem at the GrUI is the same as on your local server: avoiding name clashes for jobs. As long as you manage that locally using unique names, the same will work on the UI server.
This however may be inconvenient at times. It is usually the case when your service is not composed by a single job, but by many independent jobs that may be run concurrently as well. You still need to generate unique names for each sub-job, but if they are produced within a local uniquely named service-instance, then you may reuse the sub-job names for each instance.
This comes handy in the case of many sub-jobs: as long as the main service instance is uniquely identified, contained sub-jobs may have significant names that are easier to identify than randomly-generated ones: e.g.
    user A -> service-instance-A -+-> sub-job-1
                                  |
                                  +-> sub-job-2
                                  |
                                  etc...
    user B -> service-instance-B -+-> sub-job-1
                                  |
                                  +-> sub-job-2
                                  |
                                  etc...
 In this case, since the service-instances have unique names (A, B) we may use the same naming strategy in both cases for naming sub-jobs (1, 2,...) which makes bookkeeping a lot easier.
To reproduce a similar behaviour remotely we provide 'sessions'.
Basically, what you are doing in the local case is isolating all the equally named jobs of each service-instance within an unique sandbox. In the grid you get the same result using 'sessions': whenever you want to submit a series of non-randomly-named jobs (or even a single one) you first allocate a session, and then attach those jobs to the session. Job names within a session are guaranteed not to clash with equal job names from another session.
Note the 'non-randomly-named' tag above: you want to use sessions ALWAYS that you use any non-random job name unless you can guarantee it will be the only job with that name ON THE GRID.
This is an important notice: your job may have a non-random, but guaranteed unique name on your local host. And as long as the job will only be submitted from your local host it is OK. But if you are going to share your tools with other fellows, then they will install them locally and submit a similarly named job as well. The job name will be unique within each one's local machine, but when jobs are collected at the GrUI, they will all have the same name, which is a no-no.
USING SESSIONS
Once you see the need for using sessions, using them is quite simple: you call this function asking for a new session to be created on the remote grid access point on your behalf. The routine will return a unique session identifier which you later use to tag jobs that are to be run within that session's sandbox.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/debug`); $eg->set_error_log(`/tmp/grid/debug/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) { echo `error: couldn't init the grid\n`; exit; } else echo `OK\n`; echo `Submitting tst-job to default session...\n`; $out = array(``); if (! $eg->job_submit(`tst-job`, $out)) { echo `error: coudn't start the job\n`; exit; } else echo `OK\n`; print_r($out); echo `Submitting tst-job to a new session...\n`; $sess = $eg->session_new()(p.); echo `sess = `; print_r($sess); echo `\n`; if ($sess != FALSE) { $out = array(``); if (! $eg->job_submit(`tst-job`, $out, $sess)) echo `error: coudn't start the job\n`; else { echo `OK\n`; } $eg->session_destroy($sess); } $eg->destruct()(p.);
Parameters:
string $hint an optional string to be used for the session name
Returns: string|false session ID of the newly generated session.
Definition at line 1191 of file test/grid.php.
References $debug_grid.
Grid::session_new ($ hint = `sess`)
Create a new session.
We take control of the session system: in a previous incarnation we got the session name from the user. This is dangerous since we can not avoid clashes even with random session names provided by a user: a randomly generated name may be guaranteed unique within the user's local host namespace, but should various calls come from different hosts (e.g. HA front-ends in a cluster), it is conceivable (although improbable) that both come up with the same random number and generate a clash on the shared remote grid access point. Hence the new approach: to be true, users do not need to generate a session name themselves: they just need a way to refer to them.
This routine will generate a new session: under a given session, we guarantee that processes will be run under an isolated sandbox where non name clashes from other concurrent users will occur. Name clashes within a given session induced by the user are still the responsability of the user.
SESSIONS
The basic idea is as follows: if you are developing a service that may be called concurrently by various users, your problem at the GrUI is the same as on your local server: avoiding name clashes for jobs. As long as you manage that locally using unique names, the same will work on the UI server.
This however may be inconvenient at times. It is usually the case when your service is not composed by a single job, but by many independent jobs that may be run concurrently as well. You still need to generate unique names for each sub-job, but if they are produced within a local uniquely named service-instance, then you may reuse the sub-job names for each instance.
This comes handy in the case of many sub-jobs: as long as the main service instance is uniquely identified, contained sub-jobs may have significant names that are easier to identify than randomly-generated ones: e.g.
    user A -> service-instance-A -+-> sub-job-1
                                  |
                                  +-> sub-job-2
                                  |
                                  etc...
    user B -> service-instance-B -+-> sub-job-1
                                  |
                                  +-> sub-job-2
                                  |
                                  etc...
 In this case, since the service-instances have unique names (A, B) we may use the same naming strategy in both cases for naming sub-jobs (1, 2,...) which makes bookkeeping a lot easier.
To reproduce a similar behaviour remotely we provide 'sessions'.
Basically, what you are doing in the local case is isolating all the equally named jobs of each service-instance within an unique sandbox. In the grid you get the same result using 'sessions': whenever you want to submit a series of non-randomly-named jobs (or even a single one) you first allocate a session, and then attach those jobs to the session. Job names within a session are guaranteed not to clash with equal job names from another session.
Note the 'non-randomly-named' tag above: you want to use sessions ALWAYS that you use any non-random job name unless you can guarantee it will be the only job with that name ON THE GRID.
This is an important notice: your job may have a non-random, but guaranteed unique name on your local host. And as long as the job will only be submitted from your local host it is OK. But if you are going to share your tools with other fellows, then they will install them locally and submit a similarly named job as well. The job name will be unique within each one's local machine, but when jobs are collected at the GrUI, they will all have the same name, which is a no-no.
USING SESSIONS
Once you see the need for using sessions, using them is quite simple: you call this function asking for a new session to be created on the remote grid access point on your behalf. The routine will return a unique session identifier which you later use to tag jobs that are to be run within that session's sandbox.
Sample usage: $eg = new Grid; $eg->set_user($user); $eg->set_host($host); $eg->set_password($passwd); $eg->set_passphrase($passphrase); $eg->set_work_dir(`/tmp/grid/debug`); $eg->set_error_log(`/tmp/grid/debug/connection.err`); echo `initializing grid... `; if (!$eg->initialize()(p.)) { echo `error: couldn't init the grid\n`; exit; } else echo `OK\n`; echo `Submitting tst-job to default session...\n`; $out = array(``); if (! $eg->job_submit(`tst-job`, $out)) { echo `error: coudn't start the job\n`; exit; } else echo `OK\n`; print_r($out); echo `Submitting tst-job to a new session...\n`; $sess = $eg->session_new()(p.); echo `sess = `; print_r($sess); echo `\n`; if ($sess != FALSE) { $out = array(``); if (! $eg->job_submit(`tst-job`, $out, $sess)) echo `error: coudn't start the job\n`; else { echo `OK\n`; } $eg->session_destroy($sess); } $eg->destruct()(p.);
Parameters:
string $hint an optional string to be used for the session name
Returns: string|false session ID of the newly generated session.
Definition at line 1194 of file src/grid.php.
References $debug_grid.
Grid::set_error_log ($ errlog)
set error log
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_error_log(`./grid-services/error.log`);
Parameters:
string path to a local file where we will store the error log (i.e. stderr of the grid connection)
Definition at line 657 of file test/grid.php.
References $debug_grid.
Grid::set_error_log ($ errlog)
set error log
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_error_log(`./grid-services/error.log`);
Parameters:
string path to a local file where we will store the error log (i.e. stderr of the grid connection)
Definition at line 657 of file src/grid.php.
References $debug_grid.
Grid::set_host ($ host)
set the name of the Grid access host
In order to connect to the Grid and be able to submit jobs we need a tuple (host/user/password/passphrase), i.e. an entry point to log in, and a passphrase to unlock the grid certificate.
This method allows us to define the entry point to use to gain access to the Grid.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$host=`gridui.example.com`;
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_host($host);
Parameters:
string host name of the remote UI host
Definition at line 501 of file test/grid.php.
Grid::set_host ($ host)
set the name of the Grid access host
In order to connect to the Grid and be able to submit jobs we need a tuple (host/user/password/passphrase), i.e. an entry point to log in, and a passphrase to unlock the grid certificate.
This method allows us to define the entry point to use to gain access to the Grid.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$host=`gridui.example.com`;
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_host($host);
Parameters:
string host name of the remote UI host
Definition at line 501 of file src/grid.php.
Grid::set_passphrase ($ pass)
set the passphrase for the remote grid user
In order to connect to the Grid and be able to submit jobs we need a tuple (host/user/password/passphrase), i.e. an entry point to log in, and a passphrase to unlock the grid certificate.
After we gain access to the UI host, we must unlock our certificate which identifies ourselves as 'bona-fide' grid users.
People might have an account on any UI node for a variety of reasons, but that does not qualify them to use Grid resources. Only a central Grid authority can grant this kind of access and this is done by issuing a Certificate.
Users then must store this certificate in their account on a UI host and protect it with a suitably long passphrase. This last one is the value we provide here.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$passphrase=`pass phrase to unlock certificate`;
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_passphrase($passphrase);
Parameters:
string passphrase needed to unlock the grid certificate
Definition at line 599 of file test/grid.php.
References $debug_grid.
Grid::set_passphrase ($ pass)
set the passphrase for the remote grid user
In order to connect to the Grid and be able to submit jobs we need a tuple (host/user/password/passphrase), i.e. an entry point to log in, and a passphrase to unlock the grid certificate.
After we gain access to the UI host, we must unlock our certificate which identifies ourselves as 'bona-fide' grid users.
People might have an account on any UI node for a variety of reasons, but that does not qualify them to use Grid resources. Only a central Grid authority can grant this kind of access and this is done by issuing a Certificate.
Users then must store this certificate in their account on a UI host and protect it with a suitably long passphrase. This last one is the value we provide here.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$passphrase=`pass phrase to unlock certificate`;
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_passphrase($passphrase);
Parameters:
string passphrase needed to unlock the grid certificate
Definition at line 599 of file src/grid.php.
References $debug_grid.
Grid::set_password ($ pass)
set the password for the remote grid user/server
In order to connect to the Grid and be able to submit jobs we need a tuple (host/user/password/passphrase), i.e. an entry point to log in, and a passphrase to unlock the grid certificate.
This method allows us to specify the password to clear access to the Grid UI host.
Note that this is specific to the remote UI server selected.
Further note that gaining access to a user account on a given host does not give us rights to submit jobs: we still need to unlock our ID certificate with the appropriate passphrase. Anybody with root access to an UI host can add accounts. Further, the UI host might have other roles and host other accounts for different purposes which should not access the grid. Bottomline is that we can not trust an account on a user-controlled host to identify Grid users. For this we need to recurse to a central authority to grant final access.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$password=`password`;
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_password($password);
Parameters:
string password needed to login on to the grid UI server
Definition at line 552 of file test/grid.php.
References $debug_grid.
Grid::set_password ($ pass)
set the password for the remote grid user/server
In order to connect to the Grid and be able to submit jobs we need a tuple (host/user/password/passphrase), i.e. an entry point to log in, and a passphrase to unlock the grid certificate.
This method allows us to specify the password to clear access to the Grid UI host.
Note that this is specific to the remote UI server selected.
Further note that gaining access to a user account on a given host does not give us rights to submit jobs: we still need to unlock our ID certificate with the appropriate passphrase. Anybody with root access to an UI host can add accounts. Further, the UI host might have other roles and host other accounts for different purposes which should not access the grid. Bottomline is that we can not trust an account on a user-controlled host to identify Grid users. For this we need to recurse to a central authority to grant final access.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$password=`password`;
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_password($password);
Parameters:
string password needed to login on to the grid UI server
Definition at line 552 of file src/grid.php.
References $debug_grid.
Grid::set_user ($ user)
set the Grid user name
In order to connect to the Grid and be able to submit jobs we need a tuple (host/user/password/passphrase), i.e. an entry point to log in, and a passphrase to unlock the grid certificate.
This method allows us to define the username which will be used to log in on the grid, i.e. how do we identify ourselves to the Grid UI host.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$user=`user`;
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_user($user);
Parameters:
string user identity to use in the Grid UI host
Definition at line 464 of file test/grid.php.
References $debug_grid.
Grid::set_user ($ user)
set the Grid user name
In order to connect to the Grid and be able to submit jobs we need a tuple (host/user/password/passphrase), i.e. an entry point to log in, and a passphrase to unlock the grid certificate.
This method allows us to define the username which will be used to log in on the grid, i.e. how do we identify ourselves to the Grid UI host.
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$user=`user`;
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_user($user);
Parameters:
string user identity to use in the Grid UI host
Definition at line 464 of file src/grid.php.
References $debug_grid.
Grid::set_work_dir ($ wd)
set working directory on the Grid server
This is a directory located on the grid server where all jobs and job related information will be created. It may be a path local to the user home or a global path (usually on /tmp or /var/tmp).
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_work_dir(`./grid-services`);
Parameters:
string the remote path of the working directory
Definition at line 630 of file test/grid.php.
References $debug_grid.
Grid::set_work_dir ($ wd)
set working directory on the Grid server
This is a directory located on the grid server where all jobs and job related information will be created. It may be a path local to the user home or a global path (usually on /tmp or /var/tmp).
Sample usage: require_once './grid_config.php'; require_once './ssh.php'; require_once './grid.php';
$eg = new Grid; if ($eg == FALSE) echo `Couldn't instantiate a new Grid!\n`; $eg->set_work_dir(`./grid-services`);
Parameters:
string the remote path of the working directory
Definition at line 630 of file src/grid.php.
References $debug_grid.
Member Data Documentation
Grid::$connected
Definition at line 303 of file test/grid.php.
Grid::$entry_point
the grid entry point, should not be needed
Definition at line 267 of file test/grid.php.
Grid::$error_log
a local file to store the error log
Definition at line 279 of file test/grid.php.
Grid::$hostname
name of host that provides access to the grid
Definition at line 271 of file test/grid.php.
Grid::$initialized
Definition at line 310 of file test/grid.php.
Grid::$passphrase
key to unlock the grid access certificate
Definition at line 275 of file test/grid.php.
Grid::$password
password to login on the UI node
Definition at line 273 of file test/grid.php.
Grid::$sessions
Definition at line 317 of file test/grid.php.
Grid::$std_err
Standard error of the grid entry.
Definition at line 291 of file test/grid.php.
Grid::$std_in
Standard input of the grid entry.
Definition at line 287 of file test/grid.php.
Grid::$std_out
Standard output of the grid entry.
Definition at line 289 of file test/grid.php.
Grid::$submit_timeout
Definition at line 376 of file test/grid.php.
Grid::$sx
Definition at line 324 of file test/grid.php.
Grid::$username
user name to use to connect to the grid
Definition at line 269 of file test/grid.php.
Grid::$work_dir
a GrUI directory where we can work
Definition at line 277 of file test/grid.php.
The documentation for this class was generated from the following files:
src/grid.php
test/grid.php